config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'

  get 'mini_goals'    => 'static_pages#mini_goals'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'timer' => 'static_pages#timer'
  get 'resources' => 'static_pages#resources'  

  resources :posts


end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def home
  end

  def mini_goals
  end

  def contact
  end

  def timer
  end

  def resources
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Bryant's Webpage"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
&copy; 2015 <%= link_to "Bryant Tunbutr", root_path %>  All Rights Reserved.

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<%= link_to "Home Page", root_path, class: "navbar-brand" %>
		</div>

		<div>
			<%= link_to "About", about_path, class: "navbar-brand navbar-right " %>
		</div>

	</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <!-- Wrap all page content here -->
  <div id="wrap">

    <!-- Fixed navbar -->
    <%= render "layouts/header" %>

    <!-- Begin page content -->
    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class:"alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>


  </div>

  <div class="footer">
    <div class="container">
      <%= render "layouts/footer" %>
    </div>
  </div><!--/container-->


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<h1 ><%= @post.title %></h1>
<p ><%= @post.body %></p>
<p >
  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
  | <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About Me</h1>

<p>Just here to learn Rails</p>


<div id="rotateContainer">
<%= link_to image_tag("no_idea.jpg", alt: "image",  class:"img-responsive", :id => "no_idea_dog"  ) %>
</div>

<div id="buttons">
<%= link_to "Home Page", root_path, class: "btn btn-primary" %>
<%= link_to "Mini Goals", mini_goals_path, class: "btn btn-default" %>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<h1>Goals</h1>

<p>I started The Odin Project in December. I want to become a web developer in 2-6 months :)</p>

<h2><%= link_to "Mini Goals", mini_goals_path %></h2>

<div id="fencing">
  <%= link_to image_tag("fencing.jpg", alt: "Gryphon Fencing", class:"img-responsive" ),
  'http://rubyonrails.org/'  %>
</div>

app/views/static_pages/mini_goals.html.erb
<% provide(:title, "Mini Goals") %>

<!-- <title><%= yield(:title) %> | Bryant's Webpage</title> -->

<h1>Mini Goals</h1>
<ul>
  <li>Have fun with <a href="http://www.theodinproject.com/">The Odin Project</a></li>
  <li>Have fun with Coding Bat</li>
  <li>Have fun with Meetups and give my first talk soon...</li>
  <li>Have fun with making this Vision Board more <em>FABULOUS</em> as I gain more skills</li>
</ul>

<div id="heroes">
  <%= link_to image_tag("heroes.jpg", alt: "Heroes",  class:"img-responsive" ) %>
</div>

app/views/static_pages/resources.html.erb
<% provide(:title, "Resources") %>

<a href="http://www.Meetup.com">Meetup</a>

<p>
  Meet other coders. Can do presentations and learn, teach, collaborate with and help others
</p>

<a href="http://www.theodinproject.com/">The Odin Project</a>

<p>
  A free curriculum designed to build full stack developers
</p>

<a href="http://everydayutilitarian.com/essays/notes-on-the-odin-project/">Notes on The Odin Project
</a>

<p>
  Guide to the Odin Project
</p>

<a href="https://www.youtube.com/playlist?list=PL23ZvcdS3XPLNdRYB_QyomQsShx59tpc-">12 Rails Apps in 12 Weeks
</a>

<p>
  Awesome step by step Ruby on Rails videos
</p>

<a href="http://www.vikingcodeschool.com/posts/why-learning-to-code-is-so-damn-hard">
  Why Learning to Code is So Damn Hard
</a>

<p>
  Sums up the coding journey of many
</p>

<a href="https://www.persevy.com/">
  Persevy Timer
</a>

<p>
  Pomodoro Technique timer
</p>

<a href="http://techcrunch.com/2014/05/24/dont-believe-anyone-who-tells-you-learning-to-code-is-easy/">
  Don't Believe Anyone Who Tells You Learning to Code is Easy
</a>

<p>
  Great formula for learning.
</p>

app/views/static_pages/timer.html.erb
<% provide(:title, "Timer") %>

<h1>Timer</h1>

<!-- used with javascript and jquery functions -->
<!-- <div>Registration closes in <span id="time"></span> minutes!</div> -->



<div id='countdown'></div>

<input type="button" value="reset" id="reset" />
<input type="button" value="start" id="start" />